spring.application.name=webbanve

spring.datasource.url=jdbc:mysql://localhost:3306/movie_ticket?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Kiettran3108@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.messages.basename=messages
spring.messages.encoding=UTF-8